name: PUBLISH - NUGET
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: git fetch --tags
      - run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_ENV"
      - run: dotnet pack -p:PackageVersion=${VERSION#v} --output ${{github.workspace}} -c Release
      - run: dotnet nuget push '*.nupkg' --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
