name: PUBLISH - NUGET
on:
  push: 
    tags:
    - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: NUGET
      url: https://www.nuget.org/packages/BsBlazor
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9
      - run: git fetch --tags
      - run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_ENV"
      - run: echo "VERSION=${VERSION#v}" >> "$GITHUB_ENV"
      - run: dotnet pack -p:PackageVersion=${VERSION} --output ${{github.workspace}} -c Release
      - run: dotnet nuget push '*.nupkg' --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
